#!/bin/sh -l
# FILENAME: myjobsubmissionfile

#SBATCH -A highmem		# Allocation name
##SBATCH -p queue-name		# Queue name
#SBATCH --nodes=1		# number of nodes
#SBATCH --ntasks=100		# number of MPI tasks
#SBATCH --time=24:00:00		# wall time
#SBATCH --job-name kx_0_ky_5	# Job name
#SBATCH -o myjob.o		# Name of stdout output file
#SBATCH -e myjob.e		# Name of stderr error file
#SBATCH --mail-user=shashank11297@gmail.com
#SBATCH --mail-type=all


module load mathematica/12.3
##cd $PBS_O_WORKDIR

math < make_file.nb
##for a in {-31..29..1}
##do
##	sed -i "s/\[Tau] = $a/\[Tau] = $(($a+1))/g" num_current_delay.nb
##	sed -n -e 29p num_current_delay.nb > output
##	math < num_current_delay.nb >> output
##done
## for a in {0..60..1}
# math < input_pulse.nb
# math < num_current_delay.nb > output
for a in {0..100..1}
do
  	sed -i "s/sk = $a/sk = $(($a+1))/g" num_current_delay.nb
        math < num_current_delay.nb > output
done

